//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mohamedZakaryia_0522012
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admin_ID { get; set; }
        public string admin_USerName { get; set; }
        public string admin_Pass { get; set; }
    }
}
